### ISSUE TITLE
Loosen Yii2 requirement

### ISSUE THREAD

**Issue by timkelty** [codemonauts/yii2-cloudwatch-logs#2]
I was trying to install this alongside `craftcms/cms@3.1.22`, but couldn't because of the strict version constraint: `"yiisoft/yii2": "~2.0.15.1",`

**Comment by kringkaste** [comment]
Yeah, we'll change that. There is no reason for that.

**Comment by kringkaste** [comment]
We fixed this in the last release 1.0.5.
